--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DerDevHD/libPlayerForms
build-by-default: true
branches:
- master
projects:
  libPlayerForms:
    path: ""
    model: virion
    type: library
...
